# Generated by Django 2.2 on 2019-04-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190427_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='publisher',
        ),
    ]
