# Generated by Django 2.2 on 2019-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190617_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
