# Generated by Django 2.2 on 2019-06-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=200),
        ),
    ]
