# Generated by Django 2.1.7 on 2019-04-01 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorywisegk',
            name='created_by',
            field=models.ForeignKey(default='BodhiAI', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorywisegk',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts4', to='gk_app.TopicWise'),
        ),
        migrations.AlterField(
            model_name='datewisegk',
            name='created_by',
            field=models.ForeignKey(default='BodhiAI', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datewisegk',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts3', to='gk_app.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics3', to='gk_app.Date_Category'),
        ),
        migrations.AlterField(
            model_name='topicwise',
            name='Publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topicwise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics4', to='gk_app.CategoryWise'),
        ),
    ]
