# Generated by Django 2.1.7 on 2019-04-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0002_auto_20190401_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
