# Generated by Django 2.1.7 on 2019-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0003_auto_20190401_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datewisegk',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
