# Generated by Django 2.1.7 on 2019-04-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
