# Generated by Django 2.1.7 on 2019-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190503_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='category',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
