# Generated by Django 2.1.7 on 2019-05-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190503_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latest',
            options={},
        ),
    ]
