# Generated by Django 2.1.7 on 2019-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190507_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
